Numpy Array Operations :-

In [1]:
import numpy as np

Slicing in one-dimensional array :-

In [7]:
arr=np.arange(12)
print("This is array::",arr)
print("Length of arr::",len(arr))
print("Basic Slicing::",arr[:5])
print("Basic Slicing with step::",arr[2:11:2])
print("Negative slicing::",arr[:-1])
print("Negative Indexing::",arr[-8])

This is array:: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Length of arr:: 12
Basic Slicing:: [0 1 2 3 4]
Basic Slicing with step:: [ 2  4  6  8 10]
Negative slicing:: [ 0  1  2  3  4  5  6  7  8  9 10]
Negative Indexing:: 4


Slicing in 2-dimensional array :-

In [26]:
arr_2d=np.array([[2,4,6],
                 [8,10,12],
                 [14,16,18]]
                )
print("this is 2-d array::\n",arr_2d)
# print("shape of the array::",arr_2d.shape)
# print("dimension of the array::",arr_2d.ndim)
print("entire row::",arr_2d[2])
print("entire column::",arr_2d[:,2])
print("specific element::",arr_2d[1,2])

this is 2-d array::
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
entire row:: [14 16 18]
entire column:: [ 6 12 18]
specific element:: 12


Sorting:-

In [47]:
unsorted_arr=np.array([2, 1, 5, 3, 7, 4, 6, 8])
# sorting one-dimensional array
print("sorted 1-d arr::\n",np.sort(unsorted_arr))

# sorting 2-dimensional array
unsorted_2d_arr=np.array([[13,1,2],[5,84,8],[0,19,15]])
print("original array::\n",unsorted_2d_arr)
print("sorted 2-d array by row wise::\n",np.sort(unsorted_2d_arr,axis=1))

print("sorted 2-d array by column wise::\n",np.sort(unsorted_2d_arr,axis=0))

sorted 1-d arr::
 [1 2 3 4 5 6 7 8]
original array::
 [[13  1  2]
 [ 5 84  8]
 [ 0 19 15]]
sorted 2-d array by row wise::
 [[ 1  2 13]
 [ 5  8 84]
 [ 0 15 19]]
sorted 2-d array by column wise::
 [[ 0  1  2]
 [ 5 19  8]
 [13 84 15]]


Filter :-

In [53]:
numbers_arr=np.arange(15)
print("This is number arr::\n",numbers_arr)

even_number_arr=numbers_arr[numbers_arr%2==0]
print("even number arr::\n",even_number_arr)

odd_number_arr=numbers_arr[numbers_arr%2!=0]
print("odd number arr::\n",odd_number_arr)


This is number arr::
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
even number arr::
 [ 0  2  4  6  8 10 12 14]
odd number arr::
 [ 1  3  5  7  9 11 13]


Filter with mask :-

In [56]:
mask=numbers_arr > 5
print("number is greater than 5 ::\n",numbers_arr[mask])

number is greater than 5 ::
 [ 6  7  8  9 10 11 12 13 14]


Fancy Indexing vs np.where() :-

In [69]:
# fancy indexing
indices=[0,2,4,6,10]
new_arr=np.array([11,12,13,14,15,16,17,18,19,20,21])
print("new array is::\n",new_arr[indices])

where_result=np.where(new_arr>16)
print("where result::\t",where_result)
print("NP where::\t",new_arr[where_result])

new array is::
 [11 13 15 17 21]
where result::	 (array([ 6,  7,  8,  9, 10]),)
NP where::	 [17 18 19 20 21]


In [72]:
condition_array=np.where(new_arr>15,True,False)
print("condition array::\n",condition_array)

condition array::
 [False False False False False  True  True  True  True  True  True]


Concatenate (Adding data):-

In [75]:
x=np.array([1,2,3])
y=np.array([4,5,6])
combined_arr=np.concatenate((x,y))
print("combined array::\t",combined_arr)

combined array::	 [1 2 3 4 5 6]


Array Compatibility :-

In [77]:
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6,7])
arr_3=np.array([8,9,10])

print("compatibiliy of array is::\t",arr_1.shape==arr_2.shape)
print("compatibiliy of array is::\t",arr_1.shape==arr_3.shape)

compatibiliy of array is::	 False
compatibiliy of array is::	 True


How To add row and columns in a existing array :-

In [89]:
original_arr=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original_arr,new_row))
print("this is original array::\n",original_arr)
print("With new row array::\n",with_new_row)

new_col=np.array([[7,8],[8,12]])
with_new_col=np.hstack((original_arr,new_col))
print("with new column array::\n",with_new_col)

this is original array::
 [[1 2]
 [3 4]]
With new row array::
 [[1 2]
 [3 4]
 [5 6]]
with new column array::
 [[ 1  2  7  8]
 [ 3  4  8 12]]


How To delete an element from an array :-

In [93]:
arr = np.array([12, 22, 3, 14, 5])
deleted_arr=np.delete(arr,2)
print("after array deletion::\n",deleted_arr)

after array deletion::
 [12 22 14  5]
