Numpy Array And Basics

In [1]:
import numpy as np
import time
print(np.__version__)

2.2.3


Creating array from the list

In [2]:
arr_1d = np.array([11,12,13,14,15,16])
print("1d array is :",arr_1d)
print("first element is ::",arr_1d[2])

arr_2d =np.array([[1,2,3],[4,5,6]])
print("2d array is ::\n",arr_2d)
print("Indexing ::",arr_2d[1][0])

1d array is : [11 12 13 14 15 16]
first element is :: 13
2d array is ::
 [[1 2 3]
 [4 5 6]]
Indexing :: 4


List vs Numpy Array :-

In [3]:
py_list=[10,20,15]
print("list multiplication is ::",py_list*3)

np_array=np.array([10,20,30,15])
print("array multiplication is ::",np_array*2)

start = time.time()

number_list = [i*2 for i in range(1000000)]
print("list operation time is:",time.time()-start)

start = time.time()
number_arr=np.arange(1000000)*2
print("numpy array operation time is:",time.time()-start)

list multiplication is :: [10, 20, 15, 10, 20, 15, 10, 20, 15]
array multiplication is :: [20 40 60 30]
list operation time is: 0.058029890060424805
numpy array operation time is: 0.006081342697143555


Creating Array From Scratch

In [4]:
zeros_array=np.zeros((3,3))
print("zeros array:: \n",zeros_array)

ones_array=np.ones((3,4))
print("ones array ::\n",ones_array)

empty_array=np.empty(2)
print("array is 2 random elements::\n",empty_array)

sequence_array=np.arange(10)
print("array is sequence array elements::\n",sequence_array)
sequence_array_2=np.arange(11,31,2)
print("array is sequence array elements::\n",sequence_array_2)

# this will create an array of random num(here five) elements 
linespace_array=np.linspace(11,100,num=5,dtype=int)
print("array is linespace_array elements::\n",linespace_array)

full_array=np.full((3,3),6)
print("array is full_array elements::\n",full_array)

random_array=np.random.random((2,3))
print("array is random elements::\n",random_array)

zeros array:: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array ::
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array is 2 random elements::
 [-2.00000000e+000  6.11315289e-310]
array is sequence array elements::
 [0 1 2 3 4 5 6 7 8 9]
array is sequence array elements::
 [11 13 15 17 19 21 23 25 27 29]
array is linespace_array elements::
 [ 11  33  55  77 100]
array is full_array elements::
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
array is random elements::
 [[0.40190733 0.57132717 0.90182693]
 [0.35767637 0.72644918 0.48424022]]


Array Properties :-

In [5]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,0],
    
    ])
print("shape of the array is ::",arr.shape)
print("dimension of the array is::",arr.ndim)
print("size of the array is(elements in array ) ::",arr.size)
print("data type of the array is ::",arr.dtype)
print(len(arr.shape)==arr.ndim)

shape of the array is :: (3, 3)
dimension of the array is:: 2
size of the array is(elements in array ) :: 9
data type of the array is :: int64
True


Vector , Matrix and Tensor :-

In [6]:
vector=np.array([11,12,13,14])
print("this is vector::",vector)

matrix=np.array([[10,12,13],[14,15,16]])
print("matrix is::\n",matrix)

tensor=np.array([ 
                 [[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]],
                 ])
print("this is tensor::\n",tensor)

this is vector:: [11 12 13 14]
matrix is::
 [[10 12 13]
 [14 15 16]]
this is tensor::
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Array Reshaping :-

difference b/w ravel function and flatten function :-
- if we change in raveled array then changes is also reflects in original array and if change in flattened array then changes will not be affected in original array.

In [12]:
arr=np.arange(15).reshape((3,5))
print("original array ::\n",arr)

# this is first method to reshape the array
reshaped_arr=arr.reshape((5,3))
# print("reshaped array ::\n",reshaped_arr)

# this is second method to reshape the array 
new_reshape_arr=np.reshape(arr,shape=(3,5))
# print("new reshaped array ::\n",new_reshape_arr)

# print("#"*50)

flatten_arr=arr.flatten()
# print("flattened arr::\n",flatten_arr)

# print("#"*50)
raveled_arr=arr.ravel()
# print("ravel arr::\n",raveled_arr)

#----------------------------------------
print("#"*50)
flatten_arr[6]=800
print("original array ::\n",arr)

print("flattened arr::\n",flatten_arr)

print("#"*50)

#----------------------------------------

raveled_arr[6]=800
print("original array ::\n",arr)

print("flattened arr::\n",raveled_arr)

# Transpose
print("original array::\n",arr)
transpose_arr=arr.T
print("Transpose matrix ::\n",transpose_arr)

original array ::
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
##################################################
original array ::
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
flattened arr::
 [  0   1   2   3   4   5 800   7   8   9  10  11  12  13  14]
##################################################
original array ::
 [[  0   1   2   3   4]
 [  5 800   7   8   9]
 [ 10  11  12  13  14]]
flattened arr::
 [  0   1   2   3   4   5 800   7   8   9  10  11  12  13  14]
original array::
 [[  0   1   2   3   4]
 [  5 800   7   8   9]
 [ 10  11  12  13  14]]
Transpose matrix ::
 [[  0   5  10]
 [  1 800  11]
 [  2   7  12]
 [  3   8  13]
 [  4   9  14]]
